spring:
  application:
    name: backend

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://host.docker.internal:3306/app_db
    username: ljy
    password: test1234!

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: 1HchRUtop97fDqwLEzDCVXGwCUciU6M2pfqxrixibxzCCmpp8JJxm8 # 추후 AWS Parameter Store 로 관리예정


  # ouath 설정
  security:
    oauth2:
      client:

        registration:
          google:
            client-id: 1023711165181-f32lb6b9og6c67e5492h2vv2oqkbm0nq.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://host.docker.internal:8080/login/oauth2/code/google
            scope:
              - openid
              - profile
              - email
          naver:
            client-id: uDNK5AQiOOhG3KTEPq_t
            client-secret: Fu0yxsbvvT
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://host.docker.internal:8080/login/oauth2/code/naver
          kakao:
            client-id: 69fc3e46b56278ecabe584155e79b57c
            redirect-uri: http://host.docker.internal:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code


        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id








  redis:
    host: host.docker.internal

  kafka:
    bootstrap-servers: host.docker.internal:9092

  data:
    mongodb:
      uri: mongodb://test1234:test1234!@host.docker.internal:27017/admin



logging:
  level:
    com.querydsl: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE





cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://example.com"

front:
  url: http://localhost:3000